--------------------------------------------------------------------------------
-- Products

create table public.issues (
  id                 bigint generated by default as identity primary key,
  customer_id        bigint,
  data               jsonb,
  created_at         timestamp with time zone not null default now(),
  updated_at         timestamp with time zone not null default now(),
  resolved_at        timestamp with time zone
);
